name: threecsg
version: 1.0.0
description: >
  A port of ThreeCSG to Dart
authors:
- Nelson Silva <nelson.silva@inevo.pt>
- Tiago Cardoso <tiago.cardoso@inevo.pt>
homepage: https://github.com/threeDart/three.csg.dart
dependencies:
  browser: any
  three:
    git: git://github.com/threeDart/three.dart.git
  csg:
    git: git://github.com/threeDart/csg.dart.git

